tls_wrappers/openssl: fix build failure due to missing TDX header
/root/zhouliang/rats-tls/src/tls_wrappers/openssl/un_negotiate.c:392:3: error: unknown type name ‘sgx_quote4_t’; did you mean ‘sgx_quote3_t’?
   sgx_quote4_t *quote4 = (sgx_quote4_t *)evidence.tdx.quote;
   ^~~~~~~~~~~~
   sgx_quote3_t

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>